[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.2"
  HUGO_ENV = "production"

[[headers]]
  for = "/**"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, OPTIONS"
      Access-Control-Allow-Headers = "*"
